export default {
    //current
    PUT_CURRENT_NAV_TYPE: "PUT_CURRENT_NAV_TYPE",

    //quests
    REQUEST_QUESTS: "REQUEST_QUESTS",
    RECEIVE_QUESTS: "RECEIVE_QUESTS",

    COMPLETE_QUEST: "COMPLETE_QUEST",
    CANCEL_COMPLETE_QUEST: "CANCEL_COMPLETE_QUEST",
    EDIT_QUEST: "EDIT_QUEST",
    ADD_QUEST : "ADD_QUEST"
};
